# Generated by Django 6.1 on 2026-09-17 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emailverification_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.TextField(help_text='Short introduction used on blog cards and previews.', max_length=500)),
                ('content', models.TextField(help_text='Main blog article content.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_alt', models.CharField(blank=True, help_text='Describe the image for accessibility and SEO.', max_length=250)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords, e.g. Nairobi art, Kenyan artists, contemporary art.')),
                ('meta_title', models.CharField(blank=True, max_length=250)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('seo_score', models.PositiveIntegerField(default=0)),
                ('seo_analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.blogcategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='app_blogpos_status_8754c4_idx'), models.Index(fields=['slug'], name='app_blogpos_slug_8611b9_idx')],
            },
        ),
    ]
