# Generated by Django 6.1 on 2026-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='app_blogpos_status_8754c4_idx',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description. Ideally around 150–160 characters.', max_length=320),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title. Ideally under 60 characters.', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published', '-published_at'], name='app_blogpos_publish_e84b2e_idx'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_analysis',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_score',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
