# Generated by Django 6.1 on 2026-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_blogpost_app_blogpos_status_8754c4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The main search phrase you want this article to be found for.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Descriptive ALT text for the featured image.', max_length=250),
        ),
    ]
