# Generated by Django 6.1 on 2026-09-19 18:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogpost_focus_keyword_blogpost_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Article content'),
        ),
    ]
